export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const CREATE_CATEGORY = "CREATTE_CATEGORY";
export const FETCH_INGREDIANT = "FETCH_INGREDIANT";
export const CREATE_INGREDIANT = "CREATE_INGREDIANT";
